[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."quote"]
  runtime = "python3.9"

[functions."news"]
  runtime = "python3.9"

[functions."trending"]
  runtime = "python3.9"

[functions."movers"]
  runtime = "python3.9"

[[redirects]]
  from = "/api/quote"
  to = "/.netlify/functions/quote"
  status = 200

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200

[[redirects]]
  from = "/api/trending"
  to = "/.netlify/functions/trending"
  status = 200

[[redirects]]
  from = "/api/movers"
  to = "/.netlify/functions/movers"
  status = 200
